[env]

# bind + callback specifiers
SOZO_HOST = "localhost"
SOZO_PORT = "4443"

# tls certificates
SOZO_CLIENT_CRT = "../../python/certs/client.crt.der"
SOZO_CLIENT_KEY = "../../python/certs/client.key.der"
SOZO_SERVER_CRT = "../../python/certs/server.crt.der"
